### ISSUE TITLE
Parsing error with Unknow item 'enderitemod:enderite_ingot'

### ISSUE THREAD

**Issue by linzexin022** [P3NG00/NetheriteHorseArmorFabric#2]
Hi there, I updated your mod in my server, and I know you added the combatibility of Endrite mod. However, I don't use this mod in my server but I saw an error in server game log. I don't like to see any avoidable mistakes appears in my server. Could you fix this problem? Here's the game log:

` Parsing error loading recipe netheritehorsearmor:enderite_horse_armor_from_smithing
com.google.gson.JsonSyntaxException: Unknown item 'enderitemod:enderite_ingot'
        at net.minecraft.class_1856.method_17873(class_1856.java:165) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:401) ~[?:?]
        at net.minecraft.class_1856.method_8107(class_1856.java:165) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:147) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_29544(class_5357.java:79) ~[intermediary-server.jar:?]
        at net.minecraft.class_5357$class_5358.method_8121(class_5357.java:75) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]`

**Comment by P3NG00** [comment]
Yes, I know of this error. I don't know of a way around it at the moment but in the log it should've said a few lines before this error popped up something like 'Enderite Mod not installed, disregard related crafting error.'

♥️ ~ P3

**Comment by P3NG00** [comment]
I'll leave this open until this is actually resolved

**Comment by P3NG00** [comment]
I can leave you with a temporary fix to this issue:

1) Open the Netherite Horse Armor mod's jar file with [7Zip](https://www.7-zip.org/) 
2) Travel to 'data\netheritehorsearmor\recipes\'
3) Delete 'enderite_horse_armor_from_smithing.json'

That should leave you with no error in the console. ♥
